#!/usr/local/bin/bash
# http://www.ANetzB.de/upnp2mrtg/

# configuration
HOST="192.168.178.1"
PORT="49000"
NETCAT="nc"

# 
test -f /etc/upnp2mrtg.cfg && . /etc/upnp2mrtg.cfg
case $NETCAT in
    bash) nc="shnc" ;;
    *) nc="nc -q 1" ;;
esac

# functions
rh () {
echo "POST /upnp/control/$4 HTTP/1.0
HOST: $1:$2
CONTENT-LENGTH: $3
CONTENT-TYPE: text/xml; charset=\"utf-8\"
SOAPACTION: \"urn:schemas-upnp-org:service:$5:1#$6\""
}
sf () {
  echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<s:Envelope
	xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"
	s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
    <s:Body>
        <u:$1 xmlns:u=\"urn:schemas-upnp-org:service:$2:1\" />
     </s:Body>
</s:Envelope>"
}
ga () {
  echo "$1" | grep "<$2>" | sed -e "s/^.*<$2>//" -e "s/<\/$2>//"
}
mt () {
  echo "$((${1} / ${2})) $((${1} % ${2}))"
}
shnc () {
  exec 5<>/dev/tcp/$1/$2; cat >&5; cat <&5;
}

# get uptime
rq="`sf GetStatusInfo WANIPConnection`"
po="`rh $HOST $PORT ${#rq} WANIPConn1 WANIPConnection GetStatusInfo`

$rq"
rs="`echo "$po" | $nc $HOST $PORT 2>/dev/null`"
if [ $? -eq 0 ]; then
  ut=`ga "$rs" NewUptime`

  # calculate days + hours, minutes, seconds
  s=`mt $ut 60`
  m=`mt ${s% *} 60`
  h=`mt ${m% *} 24`
fi

# get bytes in/out
rq="`sf GetAddonInfos WANCommonInterfaceConfig`"
po="`rh $HOST $PORT ${#rq} WANCommonIFC1 WANCommonInterfaceConfig GetAddonInfos`

$rq"
rs="`echo "$po" | $nc $HOST $PORT 2>/dev/null`"

if [ $? -eq 0 ]; then
  b1=`ga "$rs" NewTotalBytesReceived`
  b2=`ga "$rs" NewTotalBytesSent`
fi

# output for mrtg
printf "%s\n%s\n%d days %.2d:%.2d:%.2d h (online)\nFritz!Box\n" \
  "${b1:-UNKNOWN}" "${b2:-UNKNOWN}" "${h% *}" "${h#* }" "${m#* }" "${s#* }"
